### ISSUE TITLE
Improve preprocessing performance

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#267]
I’m running the preprocessing part of the pipeline for the first time on a full dataset on a cluster node. So far, only `bwa mem` uses all 16 cores. MarkDuplicates uses just one core, so does PrintReads and some of the other GATK tools, so the node is not used very efficiently. I’m collecting some ideas here how to improve this, in particular because I am planning to run CAW on 1000 normal samples in the near future.

* [ ] Let Nextflow submit jobs to SLURM. This means that we cannot use `/scratch/` and are restricted by the (virtualized) network file system, but perhaps it’s worth it.
* [ ] Do not run on a full node with 16 cores, but only on 8 cores or perhaps even 4. This takes longer per sample, but overall sample throughput should be higher.
* [ ] Use samblaster instead of MarkDuplicates. See #242. This and the remaining items are recommendations in [a post by Heng Li on biostars](https://www.biostars.org/p/135031/).
* [ ] Do not re-align around indels. See #61.
* [ ] Do not recalibrate base qualities.
* [ ] Use sambamba for sorting BAMs

**Comment by szilvajuhos** [comment]
- Allowing many samples using the NAS only and not /scratch will kill the network and the storage. Also, you will have to keep many screens open that can be confusing in my experience
- tried with 8 cores only, and did not gain that much. I would say for single CPU processes scatter-gather would be likely more beneficial.
- realignment can be left out it is there only for MuTect1
- why not recalibrate base qualities?
- variant recalibration is left out from the current piper workflow, but it would be actually good to include

**Comment by marcelm** [comment]
> why not recalibrate base qualities?

See what Heng Li writes in the linked post:

> The gatk implementation is slow and most of times, it is not necessary any more. I have also seen recalibration lead to slightly unexpected results.

> variant recalibration is left out from the current piper workflow, but it would be actually good to include

As far as I know it, they do it and call variants from the recalibrated files, but they deliver the BAMs without base recalibration applied because these are way smaller.

**Comment by marcelm** [comment]
I asked Francesco and Johan Dahlberg (piper author). They confirm that they do the recalibration and use it for variant calling, but deliver the uncalibrated file. We should do the same.

**Comment by johandahlberg** [comment]
I do confirm. :wink: 

Also about the variant calibration (VQSR), we used to do it on every sample, but in a production setting it turned out that it was the step that failed the most, for unclear reasons, and then worked again on a re-run. Because of this we decided to exclude it and only run it after joint calling - which we have not been using Piper for, but @vezzi's joint calling scripts: https://github.com/vezzi/joint_variant_calling

Also I've been following this project for some time now, and it looks like you guys are doing some really nice things here. :smile:

**Comment by marcelm** [comment]
Thanks for the feedback @johandahlberg :-)

One other idea is to parallelize indel realignment by splitting up the BAM into one file per chromosome.

**Comment by szilvajuhos** [comment]
Cheers @johandahlberg , my impression was that with earlier versions of GATK many people had problems with VQSR and random crashes. Hoping it is solved by now and we can dare to use it.

**Comment by johandahlberg** [comment]
@szilvajuhos Yeah. Hopefully it will be fixed in the most recent releases.

I did a optimization for Piper where I split the entire pre-processing into approximately equal sized groups of chromosomes, that did speed things up quite a bit (from ~900 cpuh to ~600 cpuh for a 30X genome). The problem with making these kinds of optimization within one node however is that though the aim is 30X per sample there will always be samples coming in which have much higher coverage which affects the RAM usage of the tools - which might lead to crashes. However I do seem to remember that NextFlow can automatically reschedule jobs with different resource requirements, so perhaps optimistic optimization is easier to achieve with it that it was with Queue?

Feel free to ping me if you have any questions on how we solved things in Piper - while I'm the first to admit that it's not without it's flaws, by now it is a rather battle tested software that has analyzed its fair bit of genomes.

**Comment by marcelm** [comment]
I’m closing this meta-issue now because some of the things have been done and the rest should be put into individual tickets.

>Let Nextflow submit jobs to SLURM. This means that we cannot use /scratch/ and are restricted by the (virtualized) network file system, but perhaps it’s worth it.

Szilva does not like this approach very much and I don’t either. While I do think it would be possible to split the jobs in such a way that there is not too much network access going on, it would also be too complicated.

> Do not run on a full node with 16 cores, but only on 8 cores or perhaps even 4. This takes longer per sample, but overall sample throughput should be higher.

The optimizations now in place make this option not so interesting anymore, and as Johan said, running too many jobs on a single node may give us RAM problems.

> Use samblaster instead of MarkDuplicates. See #242. This and the remaining items are recommendations in a post by Heng Li on biostars.

Implemented in branch `samblaster`, see PR #280.

> Do not re-align around indels. See #61.

If we ever do this, discussion should be in that ticket.

> Do not recalibrate base qualities.

Still interesting, but less so since #321 has been merged.

> Use sambamba for sorting BAMs

Perhaps not worth it since the `samblaster` branch runs mapping and sorting in parallel.
